/**
 * This file is auto-generated by Payload.
 * This stub is used for local builds. The full types are generated at runtime by Payload.
 * Run `npx payload generate:types` to regenerate (requires a database connection).
 */

export interface Config {
  collections: {
    'blog-posts': BlogPost
    media: Media
    users: User
  }
  globals: Record<string, never>
  locale: 'de' | 'en'
  user: User & {
    collection: 'users'
  }
}

export interface BlogPost {
  id: number
  title: string
  slug: string
  publishedAt?: string | null
  category?: 'SEO' | 'Content' | 'Link Building' | 'Google Ads' | 'Social Media' | 'Allgemein' | null
  excerpt?: string | null
  coverImage?: number | Media | null
  coverImageAlt?: string | null
  author?: {
    name?: string | null
    avatar?: number | Media | null
  }
  body?: unknown
  meta?: {
    title?: string | null
    description?: string | null
    image?: number | Media | null
  }
  updatedAt: string
  createdAt: string
}

export interface Media {
  id: number
  alt?: string | null
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    card?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    hero?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
  updatedAt: string
  createdAt: string
}

export interface User {
  id: number
  name?: string | null
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  updatedAt: string
  createdAt: string
  enableAPIKey?: boolean | null
  apiKey?: string | null
  apiKeyIndex?: string | null
}
